name: SonarCloud Code Analysis

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:  # Enable manual triggering
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Disable shallow clones for better analysis relevance

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame 
          # Add any other dependencies your project needs

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Check SonarCloud status
        id: sonarcloud-check
        run: |
          SONAR_ORG="${SONAR_ORGANIZATION}"
          SONAR_PROJECT="${SONAR_PROJECT_KEY}"
          SONAR_URL="https://sonarcloud.io/api/project_badges/measure?project=${SONAR_ORG}%3A${SONAR_PROJECT}&metric=alert_status"
          SONAR_RESULT=$(curl -s -u "${SONAR_TOKEN}:" "$SONAR_URL" | jq -r '.projectStatus.status')
    
          if [ "$SONAR_RESULT" = "OK" ]; then
            echo "SonarCloud check passed";
          else
            echo "SonarCloud check failed";
            exit 1;  # Fail the workflow if SonarCloud check fails
          fi



      - name: Set SonarCloud status as check
        if: steps.sonarcloud-check.outcome == 'success'
        uses: github/script-check-action@main
        with:
          status: success
          check_name: SonarCloud Analysis 
     
