name: SonarCloud Code Analysis

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:  # Enable manual triggering
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Disable shallow clones for better analysis relevance

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame 
          # Add any other dependencies your project needs

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Check SonarCloud status (using GitHub Actions API)
        id: sonarcloud-check
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          response=$(curl -sSL -X GET "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/statuses" -H "Authorization: token $GITHUB_TOKEN")
          if [[ $(echo "$response" | jq -r '.[].context == "SonarCloud Analysis"') == 'true' ]]; then
            existing_status=$(echo "$response" | jq -r '.[] | select(.context == "SonarCloud Analysis") | .state')
            if [[ "$existing_status" == "success" ]]; then
              echo "SonarCloud check already passed";
              exit 0;
            fi
          fi

          # Perform SonarCloud analysis (optional; depends on your setup)
          # ...

          # Report SonarCloud analysis status (using a conclusion message)
          conclusion="success"  # Replace with "failure" if analysis fails
          echo "::set-output name=conclusion::$conclusion"

      - name: Report SonarCloud analysis result
        uses: actions/github-script@v5
        with:
          script: |
            github.actions.createCheckRun({
              owner: 'BENZ199',  # Replace with your username
              repo: github.repo,
              head_sha: github.sha,
              name: 'SonarCloud Analysis',
              status: 'in_progress',
              started_at: new Date().toISOString(),
            });

            const conclusion = core.getInput('conclusion');
            core.setFailed('SonarCloud analysis failed');  # Use this if necessary

            github.actions.createCheckRunCompletion({
              owner: 'BENZ199',
              repo: github.repo,
              check_run_id: ${{ steps.create-check-run.outputs.id }},
              conclusion: conclusion,
              completed_at: new Date().toISOString(),
              output: {
                title: 'SonarCloud analysis',
                summary: 'SonarCloud analysis completed successfully.',  # Update for failures
              },
            });
